### ISSUE TITLE
Attribute changes not documented ?

### ISSUE THREAD

**Issue by 3ative** [jampez77/Evri#4]
I've added a parcel and can see the attributes for it. 👍

Now, when writing an automation trigger, what does the ``outForDelivery:`` attribute get updated from/to ??

```yaml
parcels:
  - [redacted]
outForDelivery: []
availableForCollection: []
icon: mdi:package-variant-closed
friendly_name: Evri Parcels
```

Here:
![Image](https://github.com/user-attachments/assets/b037bbec-055b-4035-9a8c-4dab25894201)
